title: Blake Reitzammer
description: Notes, Thoughts and Other Items
theme: just-the-docs

url: https://fatmelvin.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
